### PR TITLE
Use shelf-pack [not ready]

### PR DESCRIPTION
**Pull request by bsudekum**
@bhousel I'm working on porting this project over to use [shelf-pack](https://github.com/mapbox/shelf-pack). Going from your suggestion to use something like that is done [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js/blob/b12df4207bd5a4ac839860c188584670a6574b68/js/symbol/glyph_atlas.js#L151), I've come with the following.

Currently in the [first test](https://github.com/mapbox/spritezero/blob/master/test/test.js#L24), I'm getting a packed object that looks like 

```js
ShelfPack {
  width: 6488,
  height: 6481,
  shelves:
   [ { y: 0, x: 1, free: 6487, width: 6488, height: 1 },
     { y: 1, x: 1416, free: 5072, width: 6488, height: 12 },
     { y: 13, x: 2167, free: 4321, width: 6488, height: 18 },
     { y: 31, x: 2904, free: 3584, width: 6488, height: 24 } ],
  stats: { '1': 1, '12': 118, '18': 120, '24': 121 },
  count: [Function] }
```

Which seems small to me since it tests for packing job with 360 objects. Any ideas on whats wrong here?

### CODE REVIEW

**Comment by bhousel** [comment]
@bsudekum  I upgraded it to shelf-pack v1.0 and made some adjustments to the code and test fixtures.. Let me know what you think!

**Comment by bsudekum** [comment]
@bhousel awesome! Will the fact fixtures changed have any effect on upstream apis?

**Comment by bhousel** [comment]
I'm not sure if it affects anything upstream, but we just changed the test fixtures in c5db7370083e9fe778a98e6565fb2b976477d278 because of changing the sort.

cc @scothis ?

**Comment by scothis** [comment]
Update the fixtures as needed.

**Pull request merged**
