### PR TITLE
Add failing test for SVG without width/height

### PR DESCRIPTION
**Pull request by tmcw**
@peterqliu can't use Illustrator-generated SVG files with spritezero because Mapnik's SVG rasterizer requires width & height attributes of the `svg` element, but Illustrator exports only `viewBox`.

@flippmoke is it possible for Mapnik to support this kind of SVG input? Unfortunately with Illustrator's popularity there are probably many SVG files like this.

### CODE REVIEW

**Comment by nickidlugash** [comment]
@tmcw @peterqliu FYI AI *does* export with `width` and `height` attributes. When saving as an svg, uncheck the box "responsive" – by default, AI has this box checked, which doesn't create the `width` and `height` attributes so that you can use responsive svgs on the web.

**Comment by flippmoke** [comment]
How do you determine the size of the image to create with out a width and height @tmcw ? I am not sure we will ever have a good answer to this question?

**Comment by peterqliu** [comment]
>How do you determine the size of the image to create with out a width and height

@flippmoke  could be a slippery slope, but can we deduce this from `viewBox` as a fallback?

**Comment by jakepruitt** [comment]
@tmcw working now with mapnik update!

**Comment by tmcw** [comment]
:raised_hands:

**Comment by peterqliu** [comment]
thanks so much for this @jakepruitt

**Pull request merged**
